### ISSUE TITLE
Tamagui web error: `Looking for theme: displayName`

### ISSUE THREAD

**Issue by prophet1996** [timothymiller/t4-app#111]
➡ [tamagui] built config and components (377ms):

        Config     ./.tamagui/tamagui.config.cjs
        Components ./.tamagui/tamagui-components.config.cjs
             ./.tamagui/t4ui-components.config.cjs
        
Tamagui failed loading "/Users//dev/tamago/apps/next/.tamagui/tamagui.config.cjs"
  
  Cannot read properties of undefined (reading 'Stack')
  TypeError: Cannot read properties of undefined (reading 'Stack')
    at Object.<anonymous> (/Users//dev/tamago/node_modules/@tamagui/core/dist/cjs/index.js:16:26)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:2258:26)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:4838:24)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at /Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/registerRequire.js:48:88
    at requireTamaguiCore (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/helpers/requireTamaguiCore.js:23:10)
    at Module.tamaguiRequire [as require] (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/registerRequire.js:48:63)
    at require (node:internal/modules/helpers:176:18)
    at ../../node_modules/@tamagui/animate-presence/dist/cjs/AnimatePresence.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui.config.cjs:316:24)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui.config.cjs:12:50)
    at ../../node_modules/@tamagui/animate-presence/dist/cjs/index.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui.config.cjs:476:31)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui.config.cjs:12:50)
    at ../../node_modules/@tamagui/collapsible/dist/cjs/Collapsible.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui.config.cjs:700:36)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui.config.cjs:12:50)
    at ../../node_modules/@tamagui/collapsible/dist/cjs/index.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui.config.cjs:808:31)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui.config.cjs:12:50)
    at ../../node_modules/@tamagui/accordion/dist/cjs/Accordion.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui.config.cjs:1917:30)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui.config.cjs:12:50)
    at ../../node_modules/@tamagui/accordion/dist/cjs/index.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui.config.cjs:2237:31)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui.config.cjs:12:50)
    at Object.<anonymous> (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui.config.cjs:32371:34)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:4838:24)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at Module.tamaguiRequire [as require] (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/registerRequire.js:64:17)
    at require (node:internal/modules/helpers:176:18)
    at bundleConfig (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/extractor/bundleConfig.js:119:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getBundledConfig (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/extractor/bundleConfig.js:61:12)
    at async loadTamagui (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/extractor/loadTamagui.js:42:57)
    at async load (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js:69:60)
    at async Object.parse (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js:86:28)
    at async extractToClassNames (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/extractor/extractToClassNames.js:62:15)
    at async Object.loader (/Users/ssddd/dev/tamago/node_modules/tamagui-loader/dist/cjs/loader.js:53:73)

  
Tamagui failed loading "/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui-components.config.cjs"
  
  Cannot read properties of undefined (reading 'Stack')
  TypeError: Cannot read properties of undefined (reading 'Stack')
    at Object.<anonymous> (/Users/ssddd/dev/tamago/node_modules/@tamagui/core/dist/cjs/index.js:16:26)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:2258:26)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at newLoader (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.newLoader (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:4838:24)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at /Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/registerRequire.js:48:88
    at requireTamaguiCore (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/helpers/requireTamaguiCore.js:23:10)
    at Module.tamaguiRequire [as require] (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/registerRequire.js:48:63)
    at require (node:internal/modules/helpers:176:18)
    at ../../node_modules/@tamagui/animate-presence/dist/cjs/AnimatePresence.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui-components.config.cjs:316:24)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui-components.config.cjs:12:50)
    at ../../node_modules/@tamagui/animate-presence/dist/cjs/index.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui-components.config.cjs:476:30)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui-components.config.cjs:12:50)
    at ../../node_modules/@tamagui/collapsible/dist/cjs/Collapsible.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui-components.config.cjs:700:36)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui-components.config.cjs:12:50)
    at ../../node_modules/@tamagui/collapsible/dist/cjs/index.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui-components.config.cjs:808:30)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui-components.config.cjs:12:50)
    at ../../node_modules/@tamagui/accordion/dist/cjs/Accordion.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui-components.config.cjs:1917:30)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui-components.config.cjs:12:50)
    at ../../node_modules/@tamagui/accordion/dist/cjs/index.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui-components.config.cjs:2237:30)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui-components.config.cjs:12:50)
    at Object.<anonymous> (/Users/ssddd/dev/tamago/apps/next/.tamagui/tamagui-components.config.cjs:30728:34)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at newLoader (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.newLoader (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:4838:24)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at Module.tamaguiRequire [as require] (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/registerRequire.js:64:17)
    at require (node:internal/modules/helpers:176:18)
    at attemptLoad (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/extractor/bundleConfig.js:191:30)
    at /Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/extractor/bundleConfig.js:206:21
    at Array.flatMap (<anonymous>)
    at loadComponents (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/extractor/bundleConfig.js:167:36)
    at bundleConfig (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/extractor/bundleConfig.js:128:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getBundledConfig (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/extractor/bundleConfig.js:61:12)
    at async loadTamagui (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/extractor/loadTamagui.js:42:57)
    at async load (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js:69:60)
    at async Object.parse (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js:86:28)
    at async extractToClassNames (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/extractor/extractToClassNames.js:62:15)
    at async Object.loader (/Users/ssddd/dev/tamago/node_modules/tamagui-loader/dist/cjs/loader.js:53:73)

  
Tamagui failed loading "/Users/ssddd/dev/tamago/apps/next/.tamagui/t4ui-components.config.cjs"
  
  Cannot read properties of undefined (reading 'Stack')
  TypeError: Cannot read properties of undefined (reading 'Stack')
    at Object.<anonymous> (/Users/ssddd/dev/tamago/node_modules/@tamagui/core/dist/cjs/index.js:16:26)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:2258:26)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at newLoader (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.newLoader (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:4838:24)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at /Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/registerRequire.js:48:88
    at requireTamaguiCore (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/helpers/requireTamaguiCore.js:23:10)
    at Module.tamaguiRequire [as require] (/Users/ssddd/dev/tamago/node_modules/@tamagui/static/dist/cjs/registerRequire.js:48:63)
    at require (node:internal/modules/helpers:176:18)
    at ../../node_modules/@tamagui/animate-presence/dist/cjs/AnimatePresence.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/t4ui-components.config.cjs:316:24)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/t4ui-components.config.cjs:12:50)
    at ../../node_modules/@tamagui/animate-presence/dist/cjs/index.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/t4ui-components.config.cjs:476:31)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/t4ui-components.config.cjs:12:50)
    at ../../node_modules/@tamagui/collapsible/dist/cjs/Collapsible.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/t4ui-components.config.cjs:700:36)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/t4ui-components.config.cjs:12:50)
    at ../../node_modules/@tamagui/collapsible/dist/cjs/index.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/t4ui-components.config.cjs:808:31)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/t4ui-components.config.cjs:12:50)
    at ../../node_modules/@tamagui/accordion/dist/cjs/Accordion.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/t4ui-components.config.cjs:1917:30)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/t4ui-components.config.cjs:12:50)
    at ../../node_modules/@tamagui/accordion/dist/cjs/index.js (/Users/ssddd/dev/tamago/apps/next/.tamagui/t4ui-components.config.cjs:2237:31)
    at __require (/Users/ssddd/dev/tamago/apps/next/.tamagui/t4ui-components.config.cjs:12:50)
    at Object.<anonymous> (/Users/ssddd/dev/tamago/apps/next/.tamagui/t4ui-components.config.cjs:32365:34)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at newLoader (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.newLoader (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (/Users/ssddd/dev/tamago/node_modules/esbuild-register/dist/node.js:4838:24)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at Module.tamaguiRequire [as require] (

  
Missing theme, an error occurred when importing your config
Got config: [Function (anonymous)] {
  displayName: 'ProxyWorm - Check excludeReactNativeWebExports',
  _isProxyWorm: true
}
Looking for theme: displayName
    Mac OS

**Comment by albbus-stack** [comment]
Try `bun clean`, `bun clean:all` and `bun pm cache rm`. Then `bun install` again and that should be it.

**Comment by prophet1996** [comment]
yes that worked!
it seems i had to bun install a few times.
it failed randomly for some packages 
 404 for some repos like 
 bun install v1.0.0 (822a00c4)
  🔍 @tamagui/next-theme [518/666] 
error: package "@tamagui/next-theme" not found registry.npmjs.org/@tamagui/next-theme 404
  🔍 @tanstack/virtual-core [830/1004] 
error: package "@tanstack/virtual-core" not found registry.npmjs.org/@tanstack/virtual-core 404
  🔍 @bacons/react-views [1014/1171] 
error: package "@bacons/react-views" not found registry.npmjs.org/@bacons/react-views 404
  🔍 @tamagui/compose-refs [1771/1829] 
error: package "@tamagui/compose-refs" not found registry.npmjs.org/@tamagui/compose-refs 404
  🔍 @sideway/formula [2991/3000] 
error: package "@sideway/formula" not found registry.npmjs.org/@sideway/formula 404
  🔍 read-yaml-file [3036/3041] ^C
