### ISSUE TITLE
error in CONFIGURE_EXPO_UPDATES phase

### ISSUE THREAD

**Issue by kxxoling** [timothymiller/t4-app#141]
`TypeError: (0 , Updates_1.getRuntimeVersionNullable) is not a function` breaks my first preview build after fresh installation.

What I have changed:

1. Update `.env.local`
2. Create a project in eas
3. update eas slug and name
4. Rename package name in `/package.json`

What I have not done (which I think is not related to my issue):

1. Supabase settings  // Because I don't suppose to use supabase as DB
2. Wrangler settings // No plan to use CF either.

Tail of full log:

```sh
...
[RUN_EXPO_DOCTOR]   react-native-screens@3.29.0 - expected version: ~3.22.0
[RUN_EXPO_DOCTOR]   react-native-svg@13.14.0 - expected version: 13.9.0
[RUN_EXPO_DOCTOR] Your project may not work correctly until you install the correct versions of the packages.
[RUN_EXPO_DOCTOR] Fix with: npx expo install --fix
[RUN_EXPO_DOCTOR] Found outdated dependencies
[RUN_EXPO_DOCTOR] One or more checks failed, indicating possible issues with the project.
[RUN_EXPO_DOCTOR] Advice: Upgrade dependencies that are using the invalid package versions.
[RUN_EXPO_DOCTOR] 
[RUN_EXPO_DOCTOR] Advice: Use 'npx expo install --check' to review and upgrade your dependencies.
[RUN_EXPO_DOCTOR] Command "expo doctor" failed.
Error: npx -y expo-doctor exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (/Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawn (/Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/@expo/turtle-spawn/dist/index.js:16:47)
    at runExpoDoctor (/Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/@expo/build-tools/dist/common/setup.js:98:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/@expo/build-tools/dist/common/setup.js:71:36
    at async BuildContext.runBuildPhase (/Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/@expo/build-tools/dist/context.js:107:28)
    at async setupAsync (/Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/@expo/build-tools/dist/common/setup.js:69:9)
    at async buildAsync (/Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/@expo/build-tools/dist/builders/android.js:38:5)
    at async runBuilderWithHooksAsync (/Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/@expo/build-tools/dist/builders/common.js:12:13)
    at async Object.androidBuilder (/Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/@expo/build-tools/dist/builders/android.js:24:16)
[PREBUILD] - Creating native project directories (./ios and ./android) and updating .gitignore
[PREBUILD] ✔ Created native project | gitignore skipped
[PREBUILD] - Updating your package.json scripts, dependencies, and main file
[PREBUILD] › Using current versions instead of recommended expo-splash-screen@~0.20.5.
[PREBUILD] - Updating your package.json scripts, dependencies, and main file
[PREBUILD] ✔ Updated package.json and added index.js entry point for iOS and Android
[PREBUILD] - Config syncing
[PREBUILD] Using node to generate images. This is much slower than using native packages.
[PREBUILD] › Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.
[PREBUILD] - Config syncing
[PREBUILD] ✔ Config synced
[PREBUILD] We detected that 'apps/expo' is a bun workspace
[PREBUILD] Running "bun install" in /var/folders/2t/vcv67wt91cs9xkbwtx4d8g7m0000gn/T/eas-build-local-nodejs/37936a24-3054-4b35-8e88-e099a8f09961/build directory
[PREBUILD] bun install v1.0.22 (b400b36c)
[PREBUILD] + @t4/api@workspace:packages/api
[PREBUILD]  + @t4/ui@workspace:packages/ui
[PREBUILD]  + app@workspace:packages/app
[PREBUILD]  + expo-app@workspace:apps/expo
[PREBUILD]  + next-app@workspace:apps/next
[PREBUILD] 
[PREBUILD]  5 packages installed [649.00ms]
[PREPARE_CREDENTIALS] Writing secrets to the project's directory
[PREPARE_CREDENTIALS] Injecting signing config into build.gradle
[CONFIGURE_EXPO_UPDATES] 
TypeError: (0 , Updates_1.getRuntimeVersionNullable) is not a function
    at configureExpoUpdatesIfInstalledAsync (/Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/@expo/build-tools/dist/utils/expoUpdates.js:120:195)
    at async /Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/@expo/build-tools/dist/builders/android.js:70:9
    at async BuildContext.runBuildPhase (/Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/@expo/build-tools/dist/context.js:107:28)
    at async buildAsync (/Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/@expo/build-tools/dist/builders/android.js:69:5)
    at async runBuilderWithHooksAsync (/Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/@expo/build-tools/dist/builders/common.js:12:13)
    at async Object.androidBuilder (/Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/@expo/build-tools/dist/builders/android.js:24:16)
    at async buildAndroidAsync (/Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/eas-cli-local-build-plugin/dist/android.js:66:12)
    at async buildAsync (/Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/eas-cli-local-build-plugin/dist/build.js:52:29)
    at async main (/Users/windrunner/.npm/_npx/dddba3c650ba3521/node_modules/eas-cli-local-build-plugin/dist/main.js:16:9)

Build failed
Unknown error. See logs of the Configure expo-updates build phase for more information.
npx exited with non-zero code: 1
    Error: build command failed.
error: script "build:android:preview" exited with code 1
error: script "build:android:preview" exited with code 1

```

**Comment by kxxoling** [comment]
Looks like it's related to https://github.com/expo/eas-cli/issues/2190 , what's the suggested workflow to update expo or other libs in T4 project?

**Comment by kxxoling** [comment]
Update: fixed
